CREATE TABLE USER 
(
  UserID INT AUTO_INCREMENT PRIMARY KEY,
  Username VARCHAR(50) UNIQUE NOT NULL,
  Name VARCHAR(100) NOT NULL,
  Email VARCHAR(100) UNIQUE NOT NULL,
  Phone VARCHAR(20),
  Password VARCHAR(100) NOT NULL,
  Role ENUM('HOST', 'GUEST', 'ADMIN') NOT NULL
);

CREATE TABLE LOCATION 
(
  LocationID INT AUTO_INCREMENT PRIMARY KEY,
  City VARCHAR(100) NOT NULL,
  State VARCHAR(100) NOT NULL,
  Country VARCHAR(100) NOT NULL,
  ZipCode VARCHAR(10)
);

CREATE TABLE PROPERTY 
(
  PropertyID INT AUTO_INCREMENT PRIMARY KEY,
  HostID INT NOT NULL,
  LocationID INT NOT NULL,
  Title VARCHAR(100) NOT NULL,
  Address VARCHAR(200) NOT NULL,
  Description TEXT,
  PricePerNight DECIMAL(10, 2) NOT NULL,
  FOREIGN KEY (HostID) REFERENCES USER(UserID) ON DELETE CASCADE,
  FOREIGN KEY (LocationID) REFERENCES LOCATION(LocationID) ON DELETE CASCADE
);

CREATE TABLE RESERVATION 
(
  ReservationID INT AUTO_INCREMENT PRIMARY KEY,
  PropertyID INT NOT NULL,
  GuestID INT NOT NULL,
  StartDate DATE NOT NULL,
  EndDate DATE NOT NULL,
  FOREIGN KEY (PropertyID) REFERENCES PROPERTY(PropertyID) ON DELETE CASCADE,
  FOREIGN KEY (GuestID) REFERENCES USER(UserID) ON DELETE CASCADE,
  CHECK(StartDate < EndDate)
);

CREATE TABLE PAYMENT 
(
  PaymentID INT AUTO_INCREMENT PRIMARY KEY,
  ReservationID INT NOT NULL,
  Amount DECIMAL(10, 2) NOT NULL,
  PaymentDate DATE NOT NULL,
  PaymentMethod VARCHAR(100),
  Status ENUM('SUCCESS', 'PROCESSING', 'FAILED') DEFAULT 'PROCESSING',
  FOREIGN KEY (ReservationID) REFERENCES RESERVATION(ReservationID) ON DELETE CASCADE
);

CREATE TABLE CANCELLATION 
(
  CancellationID INT AUTO_INCREMENT PRIMARY KEY,
  ReservationID INT NOT NULL,
  CancelDate DATE NOT NULL,
  Reason TEXT,
  RefundAmount DECIMAL(10, 2) DEFAULT 0.00,
  FOREIGN KEY (ReservationID) REFERENCES RESERVATION(ReservationID) ON DELETE CASCADE
);

CREATE TABLE REVIEW 
(
  ReviewID INT AUTO_INCREMENT PRIMARY KEY,
  PropertyID INT NOT NULL,
  GuestID INT NOT NULL,
  Rating INT CHECK (Rating BETWEEN 1 AND 5),
  Comment TEXT,
  ReviewPostDate DATE,
  FOREIGN KEY (PropertyID) REFERENCES PROPERTY(PropertyID) ON DELETE CASCADE,
  FOREIGN KEY (GuestID) REFERENCES USER(UserID) ON DELETE CASCADE
);